#!/usr/bin/env python3
"""P10 supplementary (pilot-class) evidence macros -> paper/tkde/generated/p10.tex.

Separate from generate_evidence.py, which is a frozen measured path of the
sealed campaign. Everything emitted here is supplementary evidence produced
after the freeze; each source file is digest-bound in the emitted macros.
"""
import hashlib, json, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "paper/tkde/generated/p10.tex"

def sha12(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]

def tex(s):
    return s.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")

lines = ["% generated by paper/tkde/generate_p10_evidence.py -- do not edit"]

# --- P10 pilot registry: every cited hook run must match its digests --------
reg = json.loads((ROOT / "evaluation/final-v5-wsl2/p10-pilot-evidence-v1.json").read_text())
for run in reg["runs"]:
    if run.get("superseded_by"):
        # Raw of a superseded run may be gone (the 2026-09-19 host rebuild); its
        # replacement is verified instead, and no macro cites a superseded run.
        continue
    run_dir = ROOT / run["path"]
    ev = json.loads((run_dir / "campaign-evidence.json").read_text())
    if ev.get("campaign_class") != "pilot" or ev.get("publication_eligible") is not False or ev.get("status") != "pass":
        raise SystemExit(f"p10 pilot run {run['id']}: campaign evidence is not a passing pilot")
    if ev.get("submission_commit") != run["submission_commit"]:
        raise SystemExit(f"p10 pilot run {run['id']}: submission commit differs from the registry")
    if hashlib.sha256((run_dir / "campaign-evidence.json").read_bytes()).hexdigest() != run["campaign_evidence_sha256"]:
        raise SystemExit(f"p10 pilot run {run['id']}: campaign evidence digest differs from the registry")
    h = hashlib.sha256()
    n = 0
    for rel in run["sample_files"]:
        data = (run_dir / rel).read_bytes()
        h.update(data)
        n += sum(1 for line in data.splitlines() if line.strip())
    if h.hexdigest() != run["samples_sha256"]:
        raise SystemExit(f"p10 pilot run {run['id']}: sample digest differs from the registry")
    if n != run["measured_samples"]:
        raise SystemExit(f"p10 pilot run {run['id']}: {n} samples, registry declares {run['measured_samples']}")

# --- guard: nothing downstream may read or cite a superseded pilot run ------
# A rerun replaces a run in the registries only; analyses that read raw files
# by run id and prose that names a run do not follow by themselves (the timing
# analysis kept reading runs lost in the 2026-09-19 host rebuild until
# 2026-10-05). Fail closed instead of relying on a manual sweep.
_pilot_reg = json.loads((ROOT / "evaluation/final-v5-wsl2/pilot-evidence-v1.json").read_text())
SUPERSEDED = {r["id"] for r in _pilot_reg["runs"] + reg["runs"] if r.get("superseded_by") not in (None, "", "None")}
LIVE_RUNS = {r["id"] for r in _pilot_reg["runs"] + reg["runs"]} - SUPERSEDED
for _tex in ("paper/tkde/main.tex", "paper/tkde/supplement.tex"):
    _text = (ROOT / _tex).read_text()
    for _run in sorted(SUPERSEDED):
        if re.search(re.escape(_run) + r"(?!\d)", _text):
            raise SystemExit(f"{_tex} cites superseded pilot run {_run}; cite its replacement")
# The same for the analysis scripts, where a superseded id is a read path
# (or the default of one) and not just a label.
for _script in sorted(list((ROOT / "evaluation").glob("*/analyze.py")) + list((ROOT / "evaluation").glob("*/replay.py"))):
    _text = _script.read_text()
    for _run in sorted(SUPERSEDED):
        if re.search(re.escape(_run) + r"(?!\d)", _text):
            raise SystemExit(f"{_script.relative_to(ROOT)} names superseded pilot run {_run}; point it at the replacement and rerun it")

# --- B1: held-out agent-written workload -------------------------------
hd = ROOT / "evaluation/agentworkload-heldout"
res = json.loads((hd / "results.json").read_text())
p = res["passes"][0]
n, k = p["queries"], p["lowerable"]
freeze = subprocess.run(["git", "log", "--format=%h", "-1", "--", str(hd / "questions.md")],
                        capture_output=True, text=True, cwd=ROOT).stdout.strip()
lines += [
    rf"\newcommand{{\HeldoutQueries}}{{{n}}}",
    rf"\newcommand{{\HeldoutLowerable}}{{{k}}}",
    rf"\newcommand{{\HeldoutRejected}}{{{n-k}}}",
    rf"\newcommand{{\HeldoutLowerablePct}}{{{round(100*k/n)}}}",
    rf"\newcommand{{\HeldoutResultsDigest}}{{\texttt{{{sha12(hd/'results.json')}}}}}",
    rf"\newcommand{{\HeldoutQuestionsDigest}}{{\texttt{{{sha12(hd/'questions.md')}}}}}",
    rf"\newcommand{{\HeldoutFreezeCommit}}{{\texttt{{{freeze}}}}}",
]
# classification of first rejections (by reason code, with the statement ids)
groups = {}
for r in p["results"]:
    if r["lowerable"]:
        continue
    groups.setdefault(r["reason"], []).append(r["query"])
rows = []
for code in sorted(groups):
    ids = ", ".join(sorted(groups[code]))
    rows.append(rf"\code{{{code}}} & {len(groups[code])} & {ids} \\")
lines.append(r"\newcommand{\HeldoutReasonTableBody}{%" + "\n" + "\n".join(rows) + "%\n}")
# engineering-gap / new-rule / agent-defect split, classified per statement
# after reading each rejected SQL (recorded here so the split is auditable):
#   engineering gap (Dependency rule exists): typed DATE literals q01,q02,q29;
#     sheet-advertised to_char/date_trunc q06,q12,q14,q36,q40; alias/selection
#     rules q15,q17,q32
#   new rule: column/arithmetic comparisons q19,q33; division or conditional
#     arithmetic in projections q09,q20,q38; correlated subquery q39
#   agent output defect: q25 (prose appended to the SQL, unparsable)
ENG = {"q01","q02","q29","q06","q12","q14","q36","q40","q15","q17","q32"}
NEW = {"q19","q33","q09","q20","q38","q39"}
AGENT = {"q25"}
rejected = {r["query"] for r in p["results"] if not r["lowerable"]}
assert rejected == ENG | NEW | AGENT, sorted(rejected ^ (ENG | NEW | AGENT))
counts = {"eng": len(ENG), "new": len(NEW), "agent": len(AGENT)}
# Statements whose FIRST rejection is at a construct the product sheet handed
# to the agent lists as allowed (to_char, date_trunc, "/"); checked against
# the SQL and the rejection message so the count cannot drift from the files.
SHEET = {"q06", "q12", "q14", "q36", "q40", "q09", "q38"}
assert SHEET <= rejected
for r in p["results"]:
    sql = (hd / "queries" / f"{r['query']}.sql").read_text().lower()
    at_function = ("to_char(" in sql or "date_trunc(" in sql) and r.get("reason") in ("AGGREGATE_UNSUPPORTED", "FILTER_PREDICATE_UNSUPPORTED")
    at_division = r.get("message", "").startswith("Only binary +, -, and *")
    assert (r["query"] in SHEET) == (not r["lowerable"] and (at_function or at_division)), r["query"]
lines += [
    rf"\newcommand{{\HeldoutEngineeringGaps}}{{{counts['eng']}}}",
    rf"\newcommand{{\HeldoutNewRule}}{{{counts['new']}}}",
    rf"\newcommand{{\HeldoutAgentDefects}}{{{counts['agent']}}}",
    rf"\newcommand{{\HeldoutSheetAdvertised}}{{{len(SHEET)}}}",
]

# --- B3: budget-utility sweep (admission arithmetic) -------------------
sw = json.loads((ROOT / "evaluation/budget-utility-sweep/results.json").read_text())
def coords(rows, key, total=None):
    return " ".join(f"({r['multiplier']},{round(100*r[key]/total,1) if total else round(r[key],1)})" for r in rows)
# Schema 2: one benign curve (exact set replay of the closed-form corpus).
# The schema-1 fixed-increment replay of the executed 4x arm was withdrawn
# (its "upper bound" label was wrong; see the sweep README).
if sw.get("schema_version") != 2 or "benign_executed_increments" in sw:
    raise SystemExit("budget-utility-sweep results.json is not schema 2 (single exact-replay benign curve)")
bn, ad = sw["benign"], sw["adversary"]
lines += [
    rf"\newcommand{{\SweepResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/budget-utility-sweep/results.json')}}}}}",
    rf"\newcommand{{\SweepBenignCoords}}{{{coords(bn,'admitted_pct')}}}",
    rf"\newcommand{{\SweepBitsCoords}}{{{coords(ad,'recovered_bits',11)}}}",
    rf"\newcommand{{\SweepGreedyCoords}}{{{coords(ad,'greedy_distinct_dependency',18)}}}",
]
byb = {r["multiplier"]: r for r in bn}
bya = {r["multiplier"]: r for r in ad}
for m, tag in ((0.25, "Quarter"), (0.5, "Half"), (0.75, "ThreeQuarter"), (1, "One"), (1.5, "OneHalf"), (2, "Two")):
    lines += [
        rf"\newcommand{{\SweepBenign{tag}Admitted}}{{{byb[m]['admitted']}}}",
        rf"\newcommand{{\SweepBits{tag}}}{{{bya[m]['recovered_bits']}}}",
        rf"\newcommand{{\SweepGreedy{tag}}}{{{bya[m]['greedy_distinct_dependency']}}}",
    ]
lines.append(rf"\newcommand{{\SweepBenignAuthorized}}{{{bn[0]['authorized']}}}")
_benign_corpus = json.loads((ROOT / "evaluation/finalv5benign/corpus-v2.json").read_text())
if _benign_corpus["max_dependency_facts"] != byb[1]["budget"]["D"]:
    raise SystemExit("sweep: the 1x Dependency budget is no longer the corpus's largest single footprint; the supplement's sentence must be revised")
if not (byb[1]["admitted"] < byb[1.5]["admitted"] < byb[2]["admitted"] == bn[0]["authorized"]):
    raise SystemExit("sweep: admission at 1x, 1.5x, 2x no longer reads 'not saturated, not saturated, all'; the supplement's sentence must be revised")
lines += [
    rf"\newcommand{{\SweepMaxStatementDependency}}{{{_benign_corpus['max_dependency_facts']:,}}}",
    rf"\newcommand{{\SweepClosedFormUnion}}{{{_benign_corpus['trace_union_dependency_facts']:,}}}",
]
lines.append(rf"\newcommand{{\SweepBenignFirstRefusalOne}}{{{byb[1]['first_budget_refusal']}}}")
lines.append(rf"\newcommand{{\SweepRecoverAt}}{{{min(r['multiplier'] for r in ad if r['secret_recovered'])}}}")
# --- B7: refusal timing-channel bandwidth (retained data only) ----------
tc = json.loads((ROOT / "evaluation/timing-channel/results.json").read_text())
for _run in tc["sources"]["campaigns"]:
    if _run not in LIVE_RUNS:
        raise SystemExit(f"timing-channel results.json was computed from {_run}, which is not a live registered pilot run; rerun evaluation/timing-channel/analyze.py")
if tc.get("version") != 2:
    raise SystemExit("timing-channel results.json is not schema 2 (result rows, full footprint and novel part kept apart)")
_oracle_sample = ROOT / tc["sources"]["oracle_trace_sample"]
if _oracle_sample.is_file() and hashlib.sha256(_oracle_sample.read_bytes()).hexdigest() != tc["sources"]["oracle_trace_sample_sha256"]:
    raise SystemExit("timing-channel results.json: the sealed sample its oracle sets came from has changed")
po, rt = tc["post_execution"], tc["accepted_scan_rate"]
fits = po["fits"]
def slope(v, digits=3):
    return f"{v:.{digits}f}"
lines += [
    rf"\newcommand{{\TimingResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/timing-channel/results.json')}}}}}",
    rf"\newcommand{{\TimingRefusals}}{{{po['refusals']}}}",
    rf"\newcommand{{\TimingDistinctStatements}}{{{po['distinct_statements']}}}",
    rf"\newcommand{{\TimingStatementPoints}}{{{po['statement_points']}}}",
    rf"\newcommand{{\TimingCounterChecked}}{{{tc['reconstruction']['counter_accepted_steps_reproduced']}}}",
    rf"\newcommand{{\TimingAdversaryChecked}}{{{tc['reconstruction']['adversary_steps_reproduced']}}}",
    rf"\newcommand{{\TimingWithinStepGroups}}{{{po['within_step_groups']}}}",
    rf"\newcommand{{\TimingPooledSDMS}}{{{po['pooled_sd_ms']}}}",
    rf"\newcommand{{\TimingWithinStepSDMS}}{{{po['within_step_sd_median_ms']}}}",
    rf"\newcommand{{\TimingWithinStepSDPNinetyMS}}{{{po['within_step_sd_p90_ms']}}}",
    rf"\newcommand{{\TimingFullMin}}{{{fits['full_dependency']['min']}}}",
    rf"\newcommand{{\TimingFullMax}}{{{fits['full_dependency']['max']}}}",
    rf"\newcommand{{\TimingRowsMin}}{{{fits['result_rows']['min']}}}",
    rf"\newcommand{{\TimingRowsMax}}{{{fits['result_rows']['max']}}}",
    rf"\newcommand{{\TimingNovelMin}}{{{fits['novel_dependency']['min']}}}",
    rf"\newcommand{{\TimingNovelMax}}{{{fits['novel_dependency']['max']}}}",
    rf"\newcommand{{\TimingFullSpreadMS}}{{{fits['full_dependency']['group_median_spread_ms']}}}",
    rf"\newcommand{{\TimingRowsSpreadMS}}{{{fits['result_rows']['group_median_spread_ms']}}}",
    rf"\newcommand{{\TimingNovelSpreadMS}}{{{fits['novel_dependency']['group_median_spread_ms']}}}",
    rf"\newcommand{{\TimingOneRowRefusals}}{{{po['one_result_row']['refusals']}}}",
    rf"\newcommand{{\TimingOneRowFullMin}}{{{po['one_result_row']['full_dependency_min']}}}",
    rf"\newcommand{{\TimingOneRowFullMax}}{{{po['one_result_row']['full_dependency_max']}}}",
    rf"\newcommand{{\TimingFullPooledOverSE}}{{{abs(fits['full_dependency']['pooled_slope_over_se']):.1f}}}",
    rf"\newcommand{{\TimingRowsPooledOverSE}}{{{abs(fits['result_rows']['pooled_slope_over_se']):.1f}}}",
    rf"\newcommand{{\TimingStatementOverSEMax}}{{{max(abs(fits[v]['per_statement_slope_over_se']) for v in fits):.1f}}}",
    rf"\newcommand{{\TimingAcceptedFirstMS}}{{{po['accepted_position_one_median_ms']}}}",
    rf"\newcommand{{\TimingAcceptedLaterMS}}{{{po['accepted_later_median_ms']}}}",
    rf"\newcommand{{\TimingMicrosPerFact}}{{{rt['micros_per_fact']:.2f}}}",
    rf"\newcommand{{\TimingMicrosPerFactSE}}{{{rt['se_micros_per_fact']:.2f}}}",
    rf"\newcommand{{\TimingLadderFactsMin}}{{{rt['facts_min']:,}}}",
    rf"\newcommand{{\TimingLadderFactsMax}}{{{rt['facts_max']:,}}}",
    rf"\newcommand{{\TimingFactsPerNoiseSD}}{{{rt['facts_per_noise_sd']:,}}}",
    rf"\newcommand{{\TimingCampaigns}}{{{', '.join(chr(92)+'code{'+c+'}' for c in tc['sources']['campaigns'])}}}",
]
# the manuscript's qualitative reading depends on these two facts; fail if a rerun changes them
if max(abs(fits[v]["per_statement_slope_over_se"]) for v in fits) >= 2:
    raise SystemExit("timing channel: a per-statement slope is now two standard errors from zero; the supplement's reading must be revised")
if fits["full_dependency"]["group_median_spread_ms"] >= po["pooled_sd_ms"]:
    raise SystemExit("timing channel: group medians now differ by more than the pooled noise; the supplement's reading must be revised")
body = " \\\\\n".join(f"{g['value']} & {g['n']} & {g['median_ms']} & {g['p10_ms']} & {g['p90_ms']}" for g in po["by_full_dependency"])
lines.append(r"\newcommand{\TimingByFullTableBody}{%" + "\n" + body + r" \\%" + "\n}")
names = {"result_rows": "Result rows", "full_dependency": r"Full footprint $|F_D(q)|$ (Facts)", "novel_dependency": r"Novel part $|F_D(q)\setminus K_D|$ (Facts)"}
body = " \\\\\n".join(
    f"{names[v]} & {fits[v]['min']}--{fits[v]['max']} & {fits[v]['group_median_spread_ms']} & "
    f"{slope(fits[v]['pooled_ms_per_unit'])} ({slope(fits[v]['pooled_se'])}) & {slope(fits[v]['per_statement_ms_per_unit'])} ({slope(fits[v]['per_statement_se'])})"
    for v in ("result_rows", "full_dependency", "novel_dependency"))
lines.append(r"\newcommand{\TimingFitsTableBody}{%" + "\n" + body + r" \\%" + "\n}")
pre = tc["pre_execution"]["by_row_span"]
small = [v for k, v in pre.items() if int(k) < 100000]
large = [v for k, v in pre.items() if int(k) >= 100000]
lines += [
    rf"\newcommand{{\TimingPreSmallSpanMS}}{{{min(v['min_ms'] for v in small)}--{max(v['max_ms'] for v in small)}}}",
    rf"\newcommand{{\TimingPreLargeSpanMS}}{{{min(v['min_ms'] for v in large)}--{max(v['max_ms'] for v in large)}}}",
]

# --- B4: counter comparators under one aligned failure policy -----------
ca = json.loads((ROOT / "evaluation/counter-aligned/results.json").read_text())
# The replay must have read the sealed campaign the paper cites, and the file
# it read must still be that file (it kept reading a lost campaign's sample
# until 2026-10-05; see the pilot-run guard above for the same failure).
_sealed_id = json.loads((ROOT / "evaluation/final-v5-wsl2/publication-evidence-v1.json").read_text())["campaign"]["id"]
_sealed_sample = ROOT / ca["sources"]["sealed_sample"]
if f"/raw/{_sealed_id}/" not in ca["sources"]["sealed_sample"]:
    raise SystemExit(f"counter-aligned results.json reads {ca['sources']['sealed_sample']}, not the sealed campaign {_sealed_id}; rerun evaluation/counter-aligned/replay.py")
if hashlib.sha256(_sealed_sample.read_bytes()).hexdigest() != ca["sources"]["sealed_sha256"]:
    raise SystemExit("counter-aligned results.json: the sealed sample changed since the replay")
label = {"exact": "exact set floors", "release": "release-set only", "rows": "cumulative row counter", "queries": "query counter"}
cells = {(c["arm"], c["order"]): c for c in ca["aligned"]}
ex = ca["executed_default_products"]
rows_tbl = []
for arm in ("exact", "release", "rows", "queries"):
    adm = "/".join(str(cells[(arm, o)]["admitted"]) for o in ("natural", "shuffled-v1", "novelty-first-v1"))
    exadm = "/".join(str(ex[f"{arm}/{o}"]["admitted"]) for o in ("natural", "shuffled-v1", "novelty-first-v1"))
    zero = "/".join(str(cells[(arm, o)]["nonnovel_refused"]) for o in ("natural", "shuffled-v1", "novelty-first-v1"))
    dep = "/".join(str(cells[(arm, o)]["released"][1]) for o in ("natural", "shuffled-v1", "novelty-first-v1"))
    rel = "; ".join("/".join(str(x) for x in cells[(arm, o)]["released"]) for o in ("natural", "shuffled-v1", "novelty-first-v1"))
    rows_tbl.append(f"{label[arm]} & {adm} & {exadm} & {zero} & {dep}")
lines.append(r"\newcommand{\AlignedCounterTableBody}{%" + "\n" + " \\\\\n".join(rows_tbl) + r" \\%" + "\n}")
b = ca["sources"]["budgets"]
lines += [
    rf"\newcommand{{\AlignedResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/counter-aligned/results.json')}}}}}",
    rf"\newcommand{{\AlignedSealedDigest}}{{\texttt{{{ca['sources']['sealed_sha256'][:12]}}}}}",
    rf"\newcommand{{\AlignedRowsBudget}}{{{b['rows']['max_rows']}}}",
    rf"\newcommand{{\AlignedQueriesBudget}}{{{b['queries']['max_queries']}}}",
    rf"\newcommand{{\AlignedReleaseBudget}}{{{b['release']['max_release_facts']}}}",
    rf"\newcommand{{\AlignedFullDep}}{{{ca['trace']['full_union'][1]}}}",
    rf"\newcommand{{\AlignedExactDep}}{{{max(cells[('exact', o)]['released'][1] for o in ('natural','shuffled-v1','novelty-first-v1'))}}}",
    rf"\newcommand{{\AlignedRowsNaturalAdmitted}}{{{cells[('rows','natural')]['admitted']}}}",
    rf"\newcommand{{\AlignedRowsNaturalExecuted}}{{{ex['rows/natural']['admitted']}}}",
    rf"\newcommand{{\AlignedRowsShuffledAdmitted}}{{{cells[('rows','shuffled-v1')]['admitted']}}}",
    rf"\newcommand{{\AlignedRowsShuffledExecuted}}{{{ex['rows/shuffled-v1']['admitted']}}}",
    rf"\newcommand{{\AlignedRowsNaturalReleased}}{{{'/'.join(str(x) for x in cells[('rows','natural')]['released'])}}}",
    rf"\newcommand{{\AlignedRowsNaturalExecutedReleased}}{{{'/'.join(str(x) for x in ex['rows/natural']['released'])}}}",
    rf"\newcommand{{\AlignedCounterZeroMin}}{{{min(cells[(a,o)]['nonnovel_refused'] for a in ('rows','queries') for o in ('natural','shuffled-v1','novelty-first-v1'))}}}",
    rf"\newcommand{{\AlignedCounterZeroMax}}{{{max(cells[(a,o)]['nonnovel_refused'] for a in ('rows','queries') for o in ('natural','shuffled-v1','novelty-first-v1'))}}}",
]

# --- B2: headless-agent pilot (present only after the campaign) ---------
ap = ROOT / "evaluation/agent-pilot/results.json"
if ap.exists():
    ag = json.loads(ap.read_text())
    cell = {f"{c['arm']}/{c['objective']}": c for c in ag["cells"]}
    def cellmac(prefix, c):
        return [
            rf"\newcommand{{\{prefix}Runs}}{{{c['runs']}}}",
            rf"\newcommand{{\{prefix}Correct}}{{{c['correct']}}}",
            rf"\newcommand{{\{prefix}Graded}}{{{c['graded']}}}",
            rf"\newcommand{{\{prefix}Errors}}{{{c['errors']}}}",
            rf"\newcommand{{\{prefix}StepsMedian}}{{{c['steps_median']}}}",
            rf"\newcommand{{\{prefix}StepsMax}}{{{c['steps_max']}}}",
            rf"\newcommand{{\{prefix}BudgetRefusalRuns}}{{{c['runs_with_budget_refusal']}}}",
            rf"\newcommand{{\{prefix}FirstBudgetRefusal}}{{{c['first_budget_refusal_median'] if c['first_budget_refusal_median'] is not None else '--'}}}",
            rf"\newcommand{{\{prefix}BudgetRefusals}}{{{c['refusals'].get('EXPOSURE_BUDGET_EXHAUSTED', 0)}}}",
            rf"\newcommand{{\{prefix}OtherRefusals}}{{{sum(v for k, v in c['refusals'].items() if k != 'EXPOSURE_BUDGET_EXHAUSTED')}}}",
            rf"\newcommand{{\{prefix}Cells}}{{{c['released_cells_median'] if c['released_cells_median'] is not None else '--'}}}",
            rf"\newcommand{{\{prefix}CellsMax}}{{{c['released_cells_max'] if c['released_cells_max'] is not None else '--'}}}",
            rf"\newcommand{{\{prefix}Ledger}}{{{'/'.join(str(int(x)) if x is not None else '--' for x in (c['ledger_release_median'], c['ledger_dependency_median'], c['ledger_outcome_median']))}}}",
            rf"\newcommand{{\{prefix}Width}}{{{c['interval_width_median'] if c['interval_width_median'] is not None else '--'}}}",
            rf"\newcommand{{\{prefix}WidthMin}}{{{c['interval_width_min'] if c['interval_width_min'] is not None else '--'}}}",
            rf"\newcommand{{\{prefix}Seconds}}{{{c['elapsed_s_median']}}}",
        ]
    for key, prefix in (("rls/benign", "AgentRLSBenign"), ("factgate/benign", "AgentFGBenign"),
                        ("rls/probe", "AgentRLSProbe"), ("factgate/probe", "AgentFGProbe")):
        if key in cell:
            lines += cellmac(prefix, cell[key])
    lines += [
        rf"\newcommand{{\AgentResultsDigest}}{{\texttt{{{sha12(ap)}}}}}",
        rf"\newcommand{{\AgentCampaign}}{{\texttt{{{tex(ag['campaign'])}}}}}",
        rf"\newcommand{{\AgentRuns}}{{{ag['runs']}}}",
        rf"\newcommand{{\AgentModels}}{{{tex(', '.join(sorted({m for c in ag['cells'] for m in c['models']})))}}}",
        rf"\newcommand{{\AgentTruthMax}}{{{ag['truth'].get('max_amount', '--') if ag.get('truth') else '--'}}}",
    ]

# --- B8: Passant (per-query data-flow control) on the adaptive trace -----
pc = json.loads((ROOT / "evaluation/passant-comparison/results.json").read_text())
ps = pc["summary"]; fam = ps["by_family"]
lines += [
    rf"\newcommand{{\PassantResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/passant-comparison/results.json')}}}}}",
    rf"\newcommand{{\PassantTraceDigest}}{{\texttt{{{pc['trace_corpus_sha256'][:12]}}}}}",
    rf"\newcommand{{\PassantCommit}}{{\texttt{{{ps['passant_commit']}}}}}",
    rf"\newcommand{{\PassantVersion}}{{{ps['passant_package_version']}}}",
    rf"\newcommand{{\PassantStatements}}{{{ps['statements']}}}",
    rf"\newcommand{{\PassantAnswered}}{{{ps['answered']}}}",
    rf"\newcommand{{\PassantErrors}}{{{ps['errors']}}}",
    rf"\newcommand{{\PassantMatching}}{{{ps['answered_matching_expected']}}}",
    rf"\newcommand{{\PassantPaginationMismatch}}{{{fam['pagination']['mismatches']}}}",
    rf"\newcommand{{\PassantPaginationStatements}}{{{fam['pagination']['statements']}}}",
    rf"\newcommand{{\PassantAggregateErrors}}{{{fam['repeated_aggregation']['errors'] + fam['adaptive_choice']['errors']}}}",
    rf"\newcommand{{\PassantMedianMS}}{{{ps['passant_ms_median']:.2f}}}",
    rf"\newcommand{{\PassantDirectMedianMS}}{{{ps['direct_ms_median']:.2f}}}",
    rf"\newcommand{{\PassantOverhead}}{{{ps['overhead_ratio_median']:.1f}}}",
    rf"\newcommand{{\PassantCells}}{{{ps['cumulative_cells']}}}",
]

# --- B6: throughput pilot (present only after the campaign) ---------------
tp = ROOT / "evaluation/throughput-pilot/results.json"
if tp.exists():
    th = json.loads(tp.read_text())
    rows_tbl = []
    for c in th["cells"]:
        requested = c['settled'] + c['refused'] + c.get('request_errors', 0)
        rows_tbl.append(f"{c['roots']} & {c['width']} & {c['overlap']} & {c['rounds']} & {c['novel']}/{c['settled']}/{requested} & "
                        f"{c['refused']} & "
                        f"{c['settled_per_s_median']:.0f} & {c['novel_per_s_median']:.0f} & {c['client_p50_ms_median']:.0f} & {c['client_p95_ms_median']:.0f} & "
                        f"{c['cas_conflicts']}/{c['cas_attempts']} & {'yes' if c['ledger_matches'] else 'NO'}")
    lines.append(r"\newcommand{\ThroughputTableBody}{%" + "\n" + " \\\\\n".join(rows_tbl) + r" \\%" + "\n}")
    def cellval(roots, width, overlap, key):
        for c in th["cells"]:
            if c["roots"] == roots and c["width"] == width and c["overlap"] == overlap:
                return c[key]
        return None
    lines += [
        rf"\newcommand{{\ThroughputResultsDigest}}{{\texttt{{{sha12(tp)}}}}}",
        rf"\newcommand{{\ThroughputCampaign}}{{\texttt{{{tex(th['campaign'])}}}}}",
        rf"\newcommand{{\ThroughputRounds}}{{{th['rounds']}}}",
        rf"\newcommand{{\ThroughputErrorRounds}}{{{sum(c['error_rounds'] for c in th['cells'])}}}",
        rf"\newcommand{{\ThroughputRefused}}{{{sum(c['refused'] for c in th['cells'])}}}",
        rf"\newcommand{{\ThroughputLedgerAllMatch}}{{{'all' if all(c['ledger_matches'] for c in th['cells']) else 'NOT all'}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyDisjointNPS}}{{{cellval(1,50,'disjoint','novel_per_s_median'):.0f}}}",
        rf"\newcommand{{\ThroughputFourRootFiftyDisjointNPS}}{{{cellval(4,50,'disjoint','novel_per_s_median'):.0f}}}",
        rf"\newcommand{{\ThroughputOneRootTenDisjointNPS}}{{{cellval(1,10,'disjoint','novel_per_s_median'):.0f}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyDisjointPNinetyFive}}{{{cellval(1,50,'disjoint','client_p95_ms_median'):.0f}}}",
        rf"\newcommand{{\ThroughputFourRootFiftyDisjointPNinetyFive}}{{{cellval(4,50,'disjoint','client_p95_ms_median'):.0f}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyDisjointConflicts}}{{{cellval(1,50,'disjoint','cas_conflicts')}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyDisjointAttempts}}{{{cellval(1,50,'disjoint','cas_attempts')}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyIdenticalSPS}}{{{cellval(1,50,'identical','settled_per_s_median'):.0f}}}",
        rf"\newcommand{{\ThroughputOneRootTenDisjointPNinetyFive}}{{{cellval(1,10,'disjoint','client_p95_ms_median'):.0f}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyRefused}}{{{cellval(1,50,'disjoint','refused') + cellval(1,50,'nested','refused')}}}",
        rf"\newcommand{{\ThroughputOneRootFiftyRequests}}{{{cellval(1,50,'disjoint','settled') + cellval(1,50,'disjoint','refused') + cellval(1,50,'nested','settled') + cellval(1,50,'nested','refused')}}}",
        rf"\newcommand{{\ThroughputOtherRefused}}{{{sum(c['refused'] for c in th['cells']) - cellval(1,50,'disjoint','refused') - cellval(1,50,'nested','refused')}}}",
    ]

# --- P10-R2 C4b: throughput with client resubmission (present only after the pilot) ---
tr = ROOT / "evaluation/throughput-retry/results.json"
if tr.exists():
    rt = json.loads(tr.read_text())
    def rcell(pass_, roots, width, overlap, key):
        for c in rt["cells"]:
            if c["pass"] == pass_ and c["roots"] == roots and c["width"] == width and c["overlap"] == overlap:
                return c[key]
        return None
    rows_tbl = []
    for c in rt["cells"]:
        rows_tbl.append(f"{c['pass']} & {c['roots']} & {c['width']} & {c['overlap']} & {c['client_retries']} & {c['rounds']} & "
                        f"{c['settled']}/{c['requests']} & {c['completion_pct']:.1f} & {c['settled_after_retry']} & {c['resubmissions']} & {c['refused_after_retry']} & "
                        f"{c['novel_per_s_median']:.0f} & {c['client_p95_ms_median']:.0f} & {c['end_to_end_p95_ms_median']:.0f} & {c['end_to_end_max_ms_median']:.0f} & "
                        f"{'yes' if c['ledger_matches'] else 'NO'}")
    lines.append(r"\newcommand{\RetryTableBody}{%" + "\n" + " \\\\\n".join(rows_tbl) + r" \\%" + "\n}")
    retry_cells = [c for c in rt["cells"] if c["pass"] == "retry" and c["roots"] == 1 and c["width"] == 50 and c["overlap"] in ("disjoint", "nested")]
    control_cells = [c for c in rt["cells"] if c["pass"] == "control" and c["roots"] == 1 and c["width"] == 50 and c["overlap"] in ("disjoint", "nested")]
    lines += [
        rf"\newcommand{{\RetryResultsDigest}}{{\texttt{{{sha12(tr)}}}}}",
        rf"\newcommand{{\RetryCampaign}}{{\texttt{{{tex(rt['campaign'])}}}}}",
        rf"\newcommand{{\RetryRounds}}{{{rt['rounds']}}}",
        rf"\newcommand{{\RetryK}}{{{retry_cells[0]['client_retries'] if retry_cells else 0}}}",
        rf"\newcommand{{\RetryOneRootFiftyRequests}}{{{sum(c['requests'] for c in retry_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftySettled}}{{{sum(c['settled'] for c in retry_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftyAfterRetry}}{{{sum(c['settled_after_retry'] for c in retry_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftyResubmissions}}{{{sum(c['resubmissions'] for c in retry_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftyStillRefused}}{{{sum(c['refused_after_retry'] for c in retry_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftyCompletionPct}}{{{(100 * sum(c['settled'] for c in retry_cells) / max(1, sum(c['requests'] for c in retry_cells))):.1f}}}",
        rf"\newcommand{{\RetryControlOneRootFiftyRefused}}{{{sum(c['refused'] for c in control_cells)}}}",
        rf"\newcommand{{\RetryControlOneRootFiftyRequests}}{{{sum(c['requests'] for c in control_cells)}}}",
        rf"\newcommand{{\RetryOneRootFiftyDisjointEndToEndPNinetyFive}}{{{(rcell('retry',1,50,'disjoint','end_to_end_p95_ms_median') or 0):.0f}}}",
        rf"\newcommand{{\RetryOneRootFiftyDisjointClientPNinetyFive}}{{{(rcell('retry',1,50,'disjoint','client_p95_ms_median') or 0):.0f}}}",
        rf"\newcommand{{\RetryOneRootFiftyDisjointNPS}}{{{(rcell('retry',1,50,'disjoint','novel_per_s_median') or 0):.0f}}}",
        rf"\newcommand{{\RetryFourRootFiftyStillRefused}}{{{sum(c['refused_after_retry'] for c in rt['cells'] if c['pass'] == 'retry' and c['roots'] == 4)}}}",
        rf"\newcommand{{\RetryLedgerAllMatch}}{{{'all' if all(c['ledger_matches'] for c in rt['cells']) else 'NOT all'}}}",
    ]

# --- P10-R2 B5: cost ablation (present only after the runs) ------------------
b5 = ROOT / "evaluation/b5-ablation/results.json"
if b5.exists():
    ab = json.loads(b5.read_text())
    arms, checks = ab["arms"], ab["checks"]
    def armval(arm, cell, path, default=None):
        node = arms.get(arm, {}).get(cell)
        for key in path:
            if node is None:
                return default
            node = node.get(key) if isinstance(node, dict) else None
        return default if node is None else node
    def m(arm, cell, *path):
        v = armval(arm, cell, list(path) + ["median"])
        return "--" if v is None else f"{v:.0f}"
    cells_b5 = ["S1/SF1", "S2/SF10", "S6/100k-x16"]
    rows_tbl = []
    for cell in cells_b5:
        ii = armval("iv", cell, ["arm_ii_composed_server_total_ms", "median"])
        rows_tbl.append(f"{tex(cell)} & {m('i', cell, 'pipeline_ms', 'server_total')} & {'--' if ii is None else f'{ii:.0f}'} & "
                        f"{m('iv', cell, 'pipeline_ms', 'server_total')} & {m('iv', cell, 'derivation_leaves_ms')} & {m('iv', cell, 'ledger_leaves_ms')} & "
                        f"{m('iv', cell, 'component_ms', 'business_postgresql')} & {m('iv', cell, 'component_ms', 'result_encoding')} & "
                        f"{armval('i', cell, ['settled'], 0)}/{armval('iv', cell, ['settled'], 0)}")
    lines.append(r"\newcommand{\BFiveTableBody}{%" + "\n" + " \\\\\n".join(rows_tbl) + r" \\%" + "\n}")
    def chk(cell, key, fmt="{:.0f}"):
        v = checks.get(cell, {}).get(key)
        return "--" if v is None else fmt.format(v)
    lines += [
        rf"\newcommand{{\BFiveResultsDigest}}{{\texttt{{{sha12(b5)}}}}}",
        rf"\newcommand{{\BFiveDeployments}}{{{max((armval(a, c, ['deployments'], 0) for a in arms for c in arms[a]), default=0)}}}",
        rf"\newcommand{{\BFiveSamplesPerCell}}{{{max((armval(a, c, ['settled'], 0) for a in arms for c in arms[a]), default=0)}}}",
        rf"\newcommand{{\BFiveSOneCommonPct}}{{{chk('S1/SF1', 'common_path_share_of_iv_pct', '{:.0f}')}}}",
        rf"\newcommand{{\BFiveSSixCommonPct}}{{{chk('S6/100k-x16', 'common_path_share_of_iv_pct', '{:.0f}')}}}",
        rf"\newcommand{{\BFiveSOneIminusIvsDeriv}}{{{chk('S1/SF1', 'ii_minus_i_vs_derivation_ms')}}}",
        rf"\newcommand{{\BFiveSSixIminusIvsDeriv}}{{{chk('S6/100k-x16', 'ii_minus_i_vs_derivation_ms')}}}",
        rf"\newcommand{{\BFiveSSixArmI}}{{{m('i', 'S6/100k-x16', 'pipeline_ms', 'server_total')}}}",
        rf"\newcommand{{\BFiveSSixArmIV}}{{{m('iv', 'S6/100k-x16', 'pipeline_ms', 'server_total')}}}",
        rf"\newcommand{{\BFiveSSixDerivation}}{{{m('iv', 'S6/100k-x16', 'derivation_leaves_ms')}}}",
        rf"\newcommand{{\BFiveSSixLedger}}{{{m('iv', 'S6/100k-x16', 'ledger_leaves_ms')}}}",
        rf"\newcommand{{\BFiveSOneArmI}}{{{m('i', 'S1/SF1', 'pipeline_ms', 'server_total')}}}",
        rf"\newcommand{{\BFiveSOneArmIV}}{{{m('iv', 'S1/SF1', 'pipeline_ms', 'server_total')}}}",
        rf"\newcommand{{\BFiveSTwoArmIV}}{{{m('iv', 'S2/SF10', 'pipeline_ms', 'server_total')}}}",
        rf"\newcommand{{\BFiveSTwoDerivation}}{{{m('iv', 'S2/SF10', 'derivation_leaves_ms')}}}",
    ]
    naive = ab.get("naive_benign_replay")
    if naive:
        trials = naive["trials"]
        totals = sorted(t["total_settlement_ms"] for t in trials)
        rows_n = [t["storage"]["FactRows"] for t in trials]
        bytes_n = sorted(t["storage"]["TotalBytes"] for t in trials)
        big = []
        for t in trials:
            for s in t["statements"]:
                if s["admitted"] and s["candidate_dependency_facts"] >= 900000:
                    big.append(s["insert_ms"])
        lines += [
            rf"\newcommand{{\NaiveTrials}}{{{len(trials)}}}",
            rf"\newcommand{{\NaiveAdmitted}}{{{trials[0]['admitted']}}}",
            rf"\newcommand{{\NaiveRefused}}{{{trials[0]['budget_refused']}}}",
            rf"\newcommand{{\NaiveTotalSettleSecMin}}{{{totals[0]/1000:.1f}}}",
            rf"\newcommand{{\NaiveTotalSettleSecMax}}{{{totals[-1]/1000:.1f}}}",
            rf"\newcommand{{\NaiveFactRows}}{{{rows_n[0]:,}}}",
            rf"\newcommand{{\NaiveTotalMBMin}}{{{bytes_n[0]/1e6:.0f}}}",
            rf"\newcommand{{\NaiveTotalMBMax}}{{{bytes_n[-1]/1e6:.0f}}}",
            rf"\newcommand{{\NaiveBytesPerFact}}{{{bytes_n[-1]/max(1,rows_n[0]):.0f}}}",
            rf"\newcommand{{\NaiveLargestInsertSecMin}}{{{min(big)/1000:.1f}}}" if big else r"\newcommand{\NaiveLargestInsertSecMin}{--}",
            rf"\newcommand{{\NaiveLargestInsertSecMax}}{{{max(big)/1000:.1f}}}" if big else r"\newcommand{\NaiveLargestInsertSecMax}{--}",
            rf"\newcommand{{\NaiveSweepCrossCheck}}{{{tex(naive['sweep_cross_check'].get('status', '?'))}}}",
        ]

# --- P10-R2 B5: same-input Scale replay, naive ledger vs sealed V5 settlement ---
ns_path = ROOT / "evaluation/b5-ablation/naive-scale-replay.json"
if ns_path.exists():
    ns = json.loads(ns_path.read_text())
    if ns.get("campaign_class") != "pilot" or ns.get("publication_eligible") is not False:
        raise SystemExit("naive-scale-replay.json is not pilot class")
    pub = json.loads((ROOT / "evaluation/final-v5-wsl2/publication-evidence-v1.json").read_text())
    if ns["sealed_campaign"] not in json.dumps(pub):
        raise SystemExit(f"naive-scale-replay.json reads {ns['sealed_campaign']}, which is not the sealed campaign of publication-evidence-v1.json")
    for f, digest in ns["sealed_sample_files"].items():
        if hashlib.sha256((ROOT / f).read_bytes()).hexdigest() != digest:
            raise SystemExit(f"naive-scale-replay.json: sealed sample file {f} changed since the replay")
    if not all(c["equality_checks_passed"] and len(c["naive_trials"]) == ns["trials"] for c in ns["cells"]):
        raise SystemExit("naive-scale-replay.json: an equality check failed or a trial is missing")
    def med(v):
        v = sorted(v)
        return v[len(v) // 2] if len(v) % 2 else (v[len(v) // 2 - 1] + v[len(v) // 2]) / 2
    def ratio(x):
        return f"{x:.1f}" if x < 10 else f"{x:.0f}"
    def msfmt(x):
        return f"{x:.0f}" if x >= 100 else f"{x:.1f}"
    rows_ns, ratios, by = [], [], {}
    for c in ns["cells"]:
        t = [n["candidate_total_ms"] for n in c["naive_trials"]]
        again = med([n["resettle_total_ms"] for n in c["naive_trials"]])
        v5 = c["sealed_v5"]["control_settlement_p50_ms"]
        r = med(t) / v5
        ratios.append(r)
        mb = med([n["total_bytes"] for n in c["naive_trials"]]) / 1e6
        by[(c["candidate_dependency_facts"], c["overlap_percent"])] = dict(naive=med(t), v5=v5, ratio=r, mb=mb, again=again,
            lo=min(t), hi=max(t), rows=c["naive_trials"][0]["fact_rows"], bytes=med([n["total_bytes"] for n in c["naive_trials"]]))
        rows_ns.append(f"{c['candidate_dependency_facts']:,} & {c['overlap_percent']}\\% & {c['candidate_dependency_facts'] - c['overlap_dependency_facts']:,} & "
                       f"{msfmt(v5)} & {msfmt(c['sealed_v5']['exposure_fact_store_p50_ms'])} & {msfmt(med(t))} ({msfmt(min(t))}--{msfmt(max(t))}) & "
                       f"{ratio(r)} & {msfmt(again)} & {mb:.0f}")
    big, small, mid = 1035000, 10000, 100000
    for _n in (small, mid, big):
        per = [by[(_n, o)]["ratio"] for o in (0, 50, 90, 100)]
        assert max(per) == by[(_n, 0)]["ratio"] and min(per) == by[(_n, 100)]["ratio"], _n
    lines.append(r"\newcommand{\NaiveScaleTableBody}{%" + "\n" + " \\\\\n".join(rows_ns) + r" \\%" + "\n}")
    lines += [
        rf"\newcommand{{\NaiveScaleResultsDigest}}{{\texttt{{{sha12(ns_path)}}}}}",
        rf"\newcommand{{\NaiveScaleTrials}}{{{ns['trials']}}}",
        rf"\newcommand{{\NaiveScaleCells}}{{{len(ns['cells'])}}}",
        rf"\newcommand{{\NaiveScaleSealedSamplesPerCell}}{{{ns['cells'][0]['sealed_v5']['samples']}}}",
        rf"\newcommand{{\NaiveScaleMillionZeroNaiveS}}{{{by[(big, 0)]['naive'] / 1000:.1f}}}",
        rf"\newcommand{{\NaiveScaleMillionZeroVFiveMS}}{{{by[(big, 0)]['v5']:.0f}}}",
        rf"\newcommand{{\NaiveScaleMillionZeroRatio}}{{{ratio(by[(big, 0)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleMillionFullNaiveS}}{{{by[(big, 100)]['naive'] / 1000:.1f}}}",
        rf"\newcommand{{\NaiveScaleMillionFullRatio}}{{{ratio(by[(big, 100)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleHundredKZeroRatio}}{{{ratio(by[(mid, 0)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleHundredKFullRatio}}{{{ratio(by[(mid, 100)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleTenKZeroRatio}}{{{ratio(by[(small, 0)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleTenKFullRatio}}{{{ratio(by[(small, 100)]['ratio'])}}}",
        rf"\newcommand{{\NaiveScaleTenKZeroNaiveMS}}{{{msfmt(by[(small, 0)]['naive'])}}}",
        rf"\newcommand{{\NaiveScaleTenKZeroVFiveMS}}{{{msfmt(by[(small, 0)]['v5'])}}}",
        rf"\newcommand{{\NaiveScaleRatioMin}}{{{ratio(min(ratios))}}}",
        rf"\newcommand{{\NaiveScaleRatioMax}}{{{ratio(max(ratios))}}}",
        rf"\newcommand{{\NaiveScaleFullOverZeroPctMin}}{{{min(100 * by[(n, 100)]['naive'] / by[(n, 0)]['naive'] for n in (small, mid, big)):.0f}}}",
        rf"\newcommand{{\NaiveScaleFullOverZeroPctMax}}{{{max(100 * by[(n, 100)]['naive'] / by[(n, 0)]['naive'] for n in (small, mid, big)):.0f}}}",
        rf"\newcommand{{\NaiveScaleMillionZeroMB}}{{{by[(big, 0)]['mb']:.0f}}}",
        rf"\newcommand{{\NaiveScaleMillionZeroRows}}{{{by[(big, 0)]['rows']:,}}}",
        rf"\newcommand{{\NaiveScaleBytesPerFact}}{{{by[(big, 0)]['bytes'] / by[(big, 0)]['rows']:.0f}}}",
    ]

# --- P10-R2: held-out questions under a sheet that matches the lowerer ------
sh_dir = ROOT / "evaluation/agentworkload-heldout-sheet"
if (sh_dir / "summary.json").exists():
    sm = json.loads((sh_dir / "summary.json").read_text())
    ph = json.loads((sh_dir / "posthoc-unfenced.json").read_text())
    if sm.get("campaign_class") != "pilot" or sm.get("publication_eligible") is not False:
        raise SystemExit("held-out sheet study is not pilot class")
    if sm["questions_sha256"] != hashlib.sha256((hd / "questions.md").read_bytes()).hexdigest():
        raise SystemExit("held-out sheet study did not use the frozen held-out questions")
    if sm["sheets"]["original"] != hashlib.sha256((hd / "products.md").read_bytes()).hexdigest():
        raise SystemExit("held-out sheet study: the original arm's sheet is not the held-out study's sheet")
    if ph["summary_sha256"] != hashlib.sha256((sh_dir / "summary.json").read_bytes()).hexdigest():
        raise SystemExit("posthoc-unfenced.json was not computed from the current summary.json")
    for run in sm["runs"]:
        _f = sh_dir / "results" / f"{run['arm']}-r{run['repetition']}.json"
        if hashlib.sha256(_f.read_bytes()).hexdigest() != run["results_sha256"]:
            raise SystemExit(f"held-out sheet study: {_f.name} changed since the summary")
    glog = (sh_dir / "generation.log").read_text().splitlines()
    if hashlib.sha256((sh_dir / "generation.log").read_bytes()).hexdigest() != sm["generation_log_sha256"]:
        raise SystemExit("held-out sheet study: generation.log changed since the summary")
    gen_models = {part.split("=", 1)[1] for line in glog for part in line.split() if part.startswith("model=")}
    if len(gen_models) != 1:
        raise SystemExit(f"held-out sheet study: more than one model recorded: {sorted(gen_models)}")
    so, sc = sm["arms"]["original"], sm["arms"]["corrected"]
    po, pc = ph["arms"]["original"], ph["arms"]["corrected"]
    def lst(v):
        return ", ".join(str(x) for x in v)
    def rng(v):
        return f"{min(v)}" if min(v) == max(v) else f"{min(v)}--{max(v)}"
    seven = sorted(ph["heldout_sheet_attributed_questions"])
    if set(seven) != SHEET:
        raise SystemExit("held-out sheet study: sheet-attributed question set differs from the held-out classification")
    seven_frozen = sum(sm["per_question_admitted_count"][q]["original"] + sm["per_question_admitted_count"][q]["corrected"] for q in seven)
    seven_unfenced = sum(v["original"] + v["corrected"] for v in ph["heldout_sheet_attributed_questions"].values())
    reps = len(so["admitted"])
    fenced_all = po["fenced"] + pc["fenced"]
    gained = sm["questions_gained_in_every_repetition"]
    lines += [
        rf"\newcommand{{\SheetResultsDigest}}{{\texttt{{{sha12(sh_dir / 'summary.json')}}}}}",
        rf"\newcommand{{\SheetPosthocDigest}}{{\texttt{{{sha12(sh_dir / 'posthoc-unfenced.json')}}}}}",
        rf"\newcommand{{\SheetModel}}{{\texttt{{{tex(sorted(gen_models)[0])}}}}}",
        rf"\newcommand{{\SheetReps}}{{{reps}}}",
        rf"\newcommand{{\SheetStatements}}{{{sum(r['queries'] for r in sm['runs'])}}}",
        rf"\newcommand{{\SheetHarnessRetries}}{{{sum(1 for line in glog if 'harness-failure' in line)}}}",
        rf"\newcommand{{\SheetOriginalAdmitted}}{{{lst(so['admitted'])}}}",
        rf"\newcommand{{\SheetCorrectedAdmitted}}{{{lst(sc['admitted'])}}}",
        rf"\newcommand{{\SheetOriginalTotal}}{{{so['admitted_total']}}}",
        rf"\newcommand{{\SheetCorrectedTotal}}{{{sc['admitted_total']}}}",
        rf"\newcommand{{\SheetArmStatements}}{{{so['statements_total']}}}",
        rf"\newcommand{{\SheetOriginalRange}}{{{rng(so['admitted'])}}}",
        rf"\newcommand{{\SheetCorrectedRange}}{{{rng(sc['admitted'])}}}",
        rf"\newcommand{{\SheetOriginalMedian}}{{{so['admitted_median']:g}}}",
        rf"\newcommand{{\SheetCorrectedMedian}}{{{sc['admitted_median']:g}}}",
        rf"\newcommand{{\SheetMedianDiff}}{{{sc['admitted_median'] - so['admitted_median']:g}}}",
        rf"\newcommand{{\SheetOriginalAtRemoved}}{{{rng(so['rejections_at_originally_advertised_construct'])}}}",
        rf"\newcommand{{\SheetCorrectedAtRemoved}}{{{rng(sc['rejections_at_originally_advertised_construct'])}}}",
        rf"\newcommand{{\SheetOriginalUnstable}}{{{len(so['questions_unstable'])}}}",
        rf"\newcommand{{\SheetCorrectedUnstable}}{{{len(sc['questions_unstable'])}}}",
        rf"\newcommand{{\SheetSevenStatements}}{{{len(seven) * reps * 2}}}",
        rf"\newcommand{{\SheetSevenAdmitted}}{{{seven_frozen}}}",
        rf"\newcommand{{\SheetSevenAdmittedUnfenced}}{{{seven_unfenced}}}",
        rf"\newcommand{{\SheetFencedRange}}{{{rng(fenced_all)}}}",
        rf"\newcommand{{\SheetOriginalUnfenced}}{{{lst(po['unfenced_admitted'])}}}",
        rf"\newcommand{{\SheetCorrectedUnfenced}}{{{lst(pc['unfenced_admitted'])}}}",
        rf"\newcommand{{\SheetExpenseQuestions}}{{{len(ph['expense_questions'])}}}",
        rf"\newcommand{{\SheetOriginalUnfencedExpense}}{{{lst(po['unfenced_admitted_expense_questions'])}}}",
        rf"\newcommand{{\SheetCorrectedUnfencedExpense}}{{{lst(pc['unfenced_admitted_expense_questions'])}}}",
        rf"\newcommand{{\SheetOriginalUnfencedOther}}{{{lst(po['unfenced_admitted_other_questions'])}}}",
        rf"\newcommand{{\SheetCorrectedUnfencedOther}}{{{lst(pc['unfenced_admitted_other_questions'])}}}",
        rf"\newcommand{{\SheetGainedEveryRep}}{{{len(gained)}}}",
        rf"\newcommand{{\SheetGainedEveryRepNames}}{{{', '.join('h' + q[1:] for q in gained) or 'none'}}}",
        rf"\newcommand{{\SheetLostEveryRep}}{{{len(sm['questions_lost_in_every_repetition'])}}}",
    ]

# --- raw evidence deposited outside the repository --------------------------
dep = json.loads((ROOT / "evaluation/final-v5-wsl2/raw-evidence-deposit.json").read_text())
man_path = ROOT / "evaluation/final-v5-wsl2/raw-evidence-manifest.sha256"
if hashlib.sha256(man_path.read_bytes()).hexdigest() != dep["manifest_sha256"]:
    raise SystemExit("raw-evidence-deposit.json does not describe the tracked manifest")
man_rows = [line.split("  ", 1) for line in man_path.read_text().splitlines()]
if len(man_rows) != dep["files"]:
    raise SystemExit("raw-evidence manifest and deposit record disagree on the file count")
# Where the raw files are present, they must be the deposited bytes.
_present = [(digest, ROOT / rel) for digest, rel in man_rows if (ROOT / rel).is_file()]
if _present:
    if len(_present) != len(man_rows) or sum(f.stat().st_size for _, f in _present) != dep["bytes"]:
        raise SystemExit("raw evidence on disk is not the deposited set (file count or total size differs)")
    for digest, f in _present:
        if hashlib.sha256(f.read_bytes()).hexdigest() != digest:
            raise SystemExit(f"{f}: differs from the deposited manifest")
if dep["status"] not in ("draft", "published"):
    raise SystemExit("raw-evidence-deposit.json: unknown status")
# The manuscript may print the DOI only once the record is public.
if dep["status"] != "published" and r"\RawEvidenceDOI" in (ROOT / "paper/tkde/main.tex").read_text() + (ROOT / "paper/tkde/supplement.tex").read_text():
    raise SystemExit("the manuscript cites the raw-evidence DOI but the deposit is not published")
lines += [
    rf"\newcommand{{\RawEvidenceFiles}}{{{dep['files']}}}",
    rf"\newcommand{{\RawEvidenceMB}}{{{dep['bytes'] / 1e6:.0f}}}",
    rf"\newcommand{{\RawEvidenceSealedSamples}}{{{dep['sealed_sample_files']}}}",
    rf"\newcommand{{\RawEvidenceSealedMB}}{{{dep['sealed_sample_bytes'] / 1e6:.0f}}}",
    rf"\newcommand{{\RawEvidenceRuns}}{{{dep['run_directories']}}}",
    rf"\newcommand{{\RawEvidenceArchiveMB}}{{{dep['archive']['size'] / 1e6:.0f}}}",
    rf"\newcommand{{\RawEvidenceDOI}}{{{dep['doi']}}}",
]

OUT.write_text("\n".join(lines) + "\n")
print("ok -", OUT.relative_to(ROOT), f"held-out {k}/{n}", counts)
