#!/usr/bin/env python3
"""P10 supplementary (pilot-class) evidence macros -> paper/tkde/generated/p10.tex.

Separate from generate_evidence.py, which is a frozen measured path of the
sealed campaign. Everything emitted here is supplementary evidence produced
after the freeze; each source file is digest-bound in the emitted macros.
"""
import hashlib, json, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "paper/tkde/generated/p10.tex"

def sha12(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]

def tex(s):
    return s.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")

lines = ["% generated by paper/tkde/generate_p10_evidence.py -- do not edit"]

# --- B1: held-out agent-written workload -------------------------------
hd = ROOT / "evaluation/agentworkload-heldout"
res = json.loads((hd / "results.json").read_text())
p = res["passes"][0]
n, k = p["queries"], p["lowerable"]
freeze = subprocess.run(["git", "log", "--format=%h", "-1", "--", str(hd / "questions.md")],
                        capture_output=True, text=True, cwd=ROOT).stdout.strip()
lines += [
    rf"\newcommand{{\HeldoutQueries}}{{{n}}}",
    rf"\newcommand{{\HeldoutLowerable}}{{{k}}}",
    rf"\newcommand{{\HeldoutRejected}}{{{n-k}}}",
    rf"\newcommand{{\HeldoutLowerablePct}}{{{round(100*k/n)}}}",
    rf"\newcommand{{\HeldoutResultsDigest}}{{\texttt{{{sha12(hd/'results.json')}}}}}",
    rf"\newcommand{{\HeldoutQuestionsDigest}}{{\texttt{{{sha12(hd/'questions.md')}}}}}",
    rf"\newcommand{{\HeldoutFreezeCommit}}{{\texttt{{{freeze}}}}}",
]
# classification of first rejections (by reason code, with the statement ids)
groups = {}
for r in p["results"]:
    if r["lowerable"]:
        continue
    groups.setdefault(r["reason"], []).append(r["query"])
rows = []
for code in sorted(groups):
    ids = ", ".join(sorted(groups[code]))
    rows.append(rf"\code{{{code}}} & {len(groups[code])} & {ids} \\")
lines.append(r"\newcommand{\HeldoutReasonTableBody}{%" + "\n" + "\n".join(rows) + "%\n}")
# engineering-gap / new-rule / agent-defect split, classified per statement
# after reading each rejected SQL (recorded here so the split is auditable):
#   engineering gap (Dependency rule exists): typed DATE literals q01,q02,q29;
#     sheet-advertised to_char/date_trunc q06,q12,q14,q36,q40; alias/selection
#     rules q15,q17,q32
#   new rule: column/arithmetic comparisons q19,q33; division or conditional
#     arithmetic in projections q09,q20,q38; correlated subquery q39
#   agent output defect: q25 (prose appended to the SQL, unparsable)
ENG = {"q01","q02","q29","q06","q12","q14","q36","q40","q15","q17","q32"}
NEW = {"q19","q33","q09","q20","q38","q39"}
AGENT = {"q25"}
rejected = {r["query"] for r in p["results"] if not r["lowerable"]}
assert rejected == ENG | NEW | AGENT, sorted(rejected ^ (ENG | NEW | AGENT))
counts = {"eng": len(ENG), "new": len(NEW), "agent": len(AGENT)}
lines += [
    rf"\newcommand{{\HeldoutEngineeringGaps}}{{{counts['eng']}}}",
    rf"\newcommand{{\HeldoutNewRule}}{{{counts['new']}}}",
    rf"\newcommand{{\HeldoutAgentDefects}}{{{counts['agent']}}}",
]

# --- B3: budget-utility sweep (admission arithmetic) -------------------
sw = json.loads((ROOT / "evaluation/budget-utility-sweep/results.json").read_text())
def coords(rows, key, total=None):
    return " ".join(f"({r['multiplier']},{round(100*r[key]/total,1) if total else round(r[key],1)})" for r in rows)
ex, cm, ad = sw["benign_executed_increments"], sw["benign_corpus_model"], sw["adversary"]
lines += [
    rf"\newcommand{{\SweepResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/budget-utility-sweep/results.json')}}}}}",
    rf"\newcommand{{\SweepBenignExecutedCoords}}{{{coords(ex,'completion_pct')}}}",
    rf"\newcommand{{\SweepBenignCorpusCoords}}{{{coords(cm,'completion_pct')}}}",
    rf"\newcommand{{\SweepBitsCoords}}{{{coords(ad,'recovered_bits',11)}}}",
    rf"\newcommand{{\SweepGreedyCoords}}{{{coords(ad,'greedy_distinct_dependency',18)}}}",
]
by = {r["multiplier"]: r for r in ex}
byc = {r["multiplier"]: r for r in cm}
bya = {r["multiplier"]: r for r in ad}
for m, tag in ((0.5, "Half"), (0.75, "ThreeQuarter"), (1, "One"), (1.5, "OneHalf"), (2, "Two")):
    lines += [
        rf"\newcommand{{\SweepBenign{tag}Accepted}}{{{by[m]['accepted']}}}",
        rf"\newcommand{{\SweepBenignCorpus{tag}Accepted}}{{{byc[m]['accepted']}}}",
        rf"\newcommand{{\SweepBits{tag}}}{{{bya[m]['recovered_bits']}}}",
        rf"\newcommand{{\SweepGreedy{tag}}}{{{bya[m]['greedy_distinct_dependency']}}}",
    ]
lines.append(rf"\newcommand{{\SweepBenignAuthorized}}{{{ex[0]['authorized']}}}")
lines.append(rf"\newcommand{{\SweepRecoverAt}}{{{min(r['multiplier'] for r in ad if r['secret_recovered'])}}}")
# --- B7: refusal timing-channel bandwidth (retained data only) ----------
tc = json.loads((ROOT / "evaluation/timing-channel/results.json").read_text())
po, bd, rt = tc["post_execution"], tc["bound"], tc["rate"]
lines += [
    rf"\newcommand{{\TimingResultsDigest}}{{\texttt{{{sha12(ROOT/'evaluation/timing-channel/results.json')}}}}}",
    rf"\newcommand{{\TimingRefusals}}{{{po['refusals']}}}",
    rf"\newcommand{{\TimingWithinStepGroups}}{{{po['within_step_groups']}}}",
    rf"\newcommand{{\TimingRefusedMedianMS}}{{{po['median_ms']}}}",
    rf"\newcommand{{\TimingRefusedPTenMS}}{{{po['p10_ms']}}}",
    rf"\newcommand{{\TimingRefusedPNinetyMS}}{{{po['p90_ms']}}}",
    rf"\newcommand{{\TimingRefusedMinMS}}{{{po['min_ms']}}}",
    rf"\newcommand{{\TimingRefusedMaxMS}}{{{po['max_ms']}}}",
    rf"\newcommand{{\TimingPooledSDMS}}{{{po['pooled_sd_ms']}}}",
    rf"\newcommand{{\TimingWithinStepSDMS}}{{{po['within_step_sd_median_ms']}}}",
    rf"\newcommand{{\TimingWithinStepSDPNinetyMS}}{{{po['within_step_sd_p90_ms']}}}",
    rf"\newcommand{{\TimingSlopeMSPerRow}}{{{po['ols_ms_per_row']:.3f}}}",
    rf"\newcommand{{\TimingSlopeSEMSPerRow}}{{{po['ols_se_ms_per_row']:.3f}}}",
    rf"\newcommand{{\TimingAcceptedFirstMS}}{{{po['accepted_position_one_median_ms']}}}",
    rf"\newcommand{{\TimingAcceptedLaterMS}}{{{po['accepted_later_median_ms']}}}",
    rf"\newcommand{{\TimingMicrosPerFact}}{{{rt['micros_per_fact']:.2f}}}",
    rf"\newcommand{{\TimingMicrosPerFactSE}}{{{rt['se_micros_per_fact']:.2f}}}",
    rf"\newcommand{{\TimingResolutionFacts}}{{{bd['resolution_facts']:,}}}",
    rf"\newcommand{{\TimingFactsPerRow}}{{{bd['facts_per_row']}}}",
    rf"\newcommand{{\TimingRowGuard}}{{{bd['max_rows_guard']}}}",
    rf"\newcommand{{\TimingCorpusFMax}}{{{bd['corpus']['F_max']}}}",
    rf"\newcommand{{\TimingCorpusBits}}{{{bd['corpus']['bits']:.3f}}}",
    rf"\newcommand{{\TimingRowGuardFMax}}{{{bd['row_guard']['F_max']:,}}}",
    rf"\newcommand{{\TimingRowGuardBits}}{{{bd['row_guard']['bits']:.3f}}}",
    rf"\newcommand{{\TimingLadderFMax}}{{{bd['ladder_scale']['F_max']:,}}}",
    rf"\newcommand{{\TimingLadderBits}}{{{bd['ladder_scale']['bits']:.1f}}}",
]
body = " \\\\\n".join(f"{g['rows']} & {g['n']} & {g['median_ms']} & {g['p10_ms']} & {g['p90_ms']}" for g in po["by_rows"])
lines.append(r"\newcommand{\TimingByRowsTableBody}{%" + "\n" + body + r" \\%" + "\n}")
pre = tc["pre_execution"]["by_row_span"]
small = [v for k, v in pre.items() if int(k) < 100000]
large = [v for k, v in pre.items() if int(k) >= 100000]
lines += [
    rf"\newcommand{{\TimingPreSmallSpanMS}}{{{min(v['min_ms'] for v in small)}--{max(v['max_ms'] for v in small)}}}",
    rf"\newcommand{{\TimingPreLargeSpanMS}}{{{min(v['min_ms'] for v in large)}--{max(v['max_ms'] for v in large)}}}",
]

OUT.write_text("\n".join(lines) + "\n")
print("ok -", OUT.relative_to(ROOT), f"held-out {k}/{n}", counts)
